const libraryLanguages = [
  { id: "yue", label: "粤语音乐剧" },
  { id: "en", label: "英语音乐剧" },
  { id: "de", label: "德语音乐剧" },
  { id: "fr", label: "法语音乐剧" },
];

const libraryShows = [
{
    id: "dazhuangwang",
    deployed: true,
    language: "yue",
    cardClass: "dzw",
    href: "dazhuangwang/index.html",
    title: "大状王",
    image: "dazhuangwang/assets/show-logo.png",
    prefetch: ["dazhuangwang/songs-initial.js"],
    coverLines: ["大状王"],
    originalTitle: "An impossible trial",
    meta: ["粤语", "粤拼", "注释"],
  },
{
    id: "hamilton",
    deployed: true,
    language: "en",
    cardClass: "hamilton",
    href: "Hamilton/index.html",
    title: "汉密尔顿",
    image: "Hamilton/assets/Hamilton-Logo-1.svg",
    prefetch: ["Hamilton/lyrics-initial.js"],
    meta: ["英语", "IPA", "中文对照"],
  },
{
    id: "jesus-christ-superstar-1996-london",
    language: "en",
    cardClass: "jesus-christ-superstar",
    href: "jesus-christ-superstar-1996-london/index.html",
    title: "耶稣基督万世巨星",
    image: "jesus-christ-superstar-1996-london/assets/show-logo.png",
    originalTitle: "Jesus Christ Superstar · 1996 London Cast",
    meta: ["英语", "IPA", "中文对照"],
  },
{
    id: "les-miserables",
    language: "en",
    cardClass: "lesmis",
    href: "les-miserables/index.html",
    title: "悲惨世界",
    image: "les-miserables/assets/show-logo.png",
    coverLines: ["悲惨", "世界"],
    originalTitle: "Les Misérables",
    meta: ["英语", "IPA", "中文对照"],
  },
{
    id: "moulin-rouge",
    language: "en",
    cardClass: "moulin",
    href: "moulin-rouge/index.html",
    title: "红磨坊",
    image: "moulin-rouge/assets/show-logo.png",
    originalTitle: "Moulin Rouge! The Musical",
    meta: ["英语", "IPA", "中文对照"],
  },
{
    id: "chicago",
    language: "en",
    cardClass: "chicago",
    href: "chicago/index.html",
    title: "芝加哥",
    image: "chicago/assets/show-logo.png",
    originalTitle: "Chicago",
    meta: ["英语", "IPA", "中文对照"],
  },
{
    id: "dear-evan-hansen",
    language: "en",
    cardClass: "dear-evan-hansen",
    href: "dear-evan-hansen/index.html",
    title: "致埃文·汉森",
    image: "dear-evan-hansen/assets/show-logo.png",
    originalTitle: "Dear Evan Hansen",
    meta: ["英语", "IPA", "中文对照"],
  },
{
    id: "six-the-musical",
    language: "en",
    cardClass: "six-the-musical",
    href: "six-the-musical/index.html",
    title: "六位王后",
    image: "six-the-musical/assets/show-logo.webp",
    originalTitle: "SIX",
    meta: ["英语", "IPA", "中文对照"],
  },
{
    id: "suffs",
    language: "en",
    cardClass: "suffs",
    href: "suffs/index.html",
    title: "女权先驱",
    image: "suffs/assets/show-logo.png",
    originalTitle: "Suffs",
    meta: ["英语", "IPA", "中文对照"],
  },
{
    id: "sunset-boulevard",
    language: "en",
    cardClass: "sunset-boulevard",
    href: "sunset-boulevard/index.html",
    title: "日落大道",
    image: "sunset-boulevard/assets/show-logo.jpg",
    originalTitle: "Sunset Boulevard",
    meta: ["英语", "IPA", "中文对照"],
  },
{
    id: "phantom-of-the-opera",
    deployed: true,
    language: "en",
    cardClass: "phantom",
    href: "phantom-of-the-opera/index.html",
    title: "剧院魅影",
    image: "phantom-of-the-opera/assets/show-logo.png",
    prefetch: ["phantom-of-the-opera/songs-initial.js"],
    originalTitle: "The Phantom of the Opera",
    meta: ["英语", "IPA", "中文对照"],
  },
{
    id: "love-never-dies",
    deployed: true,
    language: "en",
    cardClass: "love-never-dies",
    href: "love-never-dies/index.html",
    title: "真爱不死",
    image: "love-never-dies/assets/show-title-logo.webp",
    prefetch: ["love-never-dies/songs-initial.js"],
    originalTitle: "Love Never Dies",
    meta: ["英语", "IPA", "中文对照"],
  },
{
    id: "elisabeth-das-musical",
    language: "de",
    cardClass: "elisabeth",
    href: "elisabeth-das-musical/index.html",
    title: "伊丽莎白",
    image: "elisabeth-das-musical/assets/show-logo.png",
    originalTitle: "Elisabeth",
    meta: ["德语", "IPA", "中英对照"],
  },
{
    id: "mozart-das-musical",
    language: "de",
    cardClass: "mozart-musical",
    href: "mozart-das-musical/index.html",
    title: "莫扎特！",
    image: "mozart-das-musical/assets/show-logo.png",
    originalTitle: "Mozart! Das Musical",
    meta: ["德语", "IPA", "中英对照"],
  },
{
    id: "tanz-der-vampire",
    language: "de",
    cardClass: "tanz-der-vampire",
    href: "tanz-der-vampire/index.html",
    title: "吸血鬼之舞",
    image: "tanz-der-vampire/assets/show-logo.png",
    originalTitle: "Tanz der Vampire",
    meta: ["德语", "IPA", "中英对照"],
  },
{
    id: "ludwig-ii-sehnsucht-nach-dem-paradies",
    language: "de",
    cardClass: "ludwig-ii",
    href: "ludwig-ii-sehnsucht-nach-dem-paradies/index.html",
    title: "路德维希二世：向往天堂",
    image: "ludwig-ii-sehnsucht-nach-dem-paradies/assets/show-logo.jpg",
    originalTitle: "Ludwig II - Sehnsucht nach dem Paradies",
    meta: ["德语", "IPA", "中英对照"],
  },
{
    id: "dracula-das-musical",
    language: "de",
    cardClass: "dracula-das-musical",
    href: "dracula-das-musical/index.html",
    title: "德古拉",
    image: "dracula-das-musical/assets/show-logo.jpg",
    originalTitle: "Dracula - Das Musical",
    meta: ["德语", "IPA", "中英对照"],
  },
{
    id: "rebecca-das-musical",
    language: "de",
    cardClass: "rebecca-das-musical",
    href: "rebecca-das-musical/index.html",
    title: "蝴蝶梦",
    image: "rebecca-das-musical/assets/show-logo.png",
    originalTitle: "Rebecca",
    meta: ["德语", "IPA", "中英对照"],
  },
{
    id: "the-greatest-showman",
    language: "en",
    cardClass: "the-greatest-showman",
    href: "the-greatest-showman/index.html",
    title: "马戏之王",
    image: "the-greatest-showman/assets/show-logo.png",
    originalTitle: "The Greatest Showman",
    meta: ["英语", "IPA", "中文对照"],
  },
{
    id: "epic-the-musical",
    language: "en",
    cardClass: "epic-the-musical",
    href: "epic-the-musical/index.html",
    title: "EPIC",
    image: "epic-the-musical/assets/show-logo.png",
    originalTitle: "EPIC",
    meta: ["英语", "IPA", "中文对照"],
  },
{
    id: "come-from-away",
    language: "en",
    cardClass: "come-from-away",
    href: "come-from-away/index.html",
    title: "来自远方",
    image: "come-from-away/assets/show-logo.jpg",
    prefetch: ["come-from-away/songs-initial.js"],
    originalTitle: "Come From Away · Original Broadway Cast Recording",
    meta: ["英语", "IPA", "中文对照"],
  },
{
    id: "rent",
    language: "en",
    cardClass: "rent",
    href: "rent/index.html",
    title: "吉屋出租",
    image: "rent/assets/show-logo.jpg",
    prefetch: ["rent/songs-initial.js"],
    originalTitle: "Rent · Original Broadway Cast",
    meta: ["英语", "IPA", "中文对照"],
  },
{
    id: "tick-tick-boom",
    language: "en",
    cardClass: "tick-tick-boom",
    href: "tick-tick-boom/index.html",
    title: "倒数时刻",
    image: "tick-tick-boom/assets/show-logo.jpg",
    prefetch: ["tick-tick-boom/songs-initial.js"],
    originalTitle: "tick, tick...BOOM! · Original Off-Broadway Cast Recording",
    meta: ["英语", "IPA", "中文对照"],
  },
{
    id: "wicked",
    language: "en",
    cardClass: "wicked",
    href: "wicked/index.html",
    title: "魔法坏女巫",
    image: "wicked/assets/show-logo.jpg",
    prefetch: ["wicked/songs-initial.js"],
    originalTitle: "Wicked · Original Broadway Cast Recording (2003)",
    meta: ["英语", "IPA", "中文对照"],
  },
{
    id: "hadestown",
    language: "en",
    cardClass: "hadestown",
    href: "hadestown/index.html",
    title: "冥城",
    image: "hadestown/assets/show-logo.jpg",
    prefetch: ["hadestown/songs-initial.js"],
    originalTitle: "Hadestown · Original Broadway Cast Recording",
    meta: ["英语", "IPA", "中文对照"],
  },
{
    id: "les-dix-commandements",
    language: "fr",
    cardClass: "les-dix-commandements",
    href: "les-dix-commandements/index.html",
    title: "十诫",
    image: "les-dix-commandements/assets/show-logo.jpg",
    prefetch: ["les-dix-commandements/songs-initial.js"],
    originalTitle: "Les Dix Commandements · 2000 French Cast",
    meta: ["法语", "IPA", "中英对照"],
  },
{
    id: "rouge-et-noir",
    deployed: true,
    language: "fr",
    cardClass: "rouge",
    href: "rouge-et-noir/index.html",
    title: "摇滚红与黑",
    image: "rouge-et-noir/assets/show-logo.png",
    prefetch: ["rouge-et-noir/songs-initial.js"],
    coverLines: ["摇滚", "红与黑"],
    originalTitle: "Le Rouge et le Noir",
    meta: ["法语", "IPA", "中英对照"],
  },
{
    id: "le-petit-prince-2cd",
    language: "fr",
    cardClass: "le-petit-prince",
    href: "le-petit-prince-2cd/index.html",
    title: "小王子",
    image: "le-petit-prince-2cd/assets/show-logo.png",
    originalTitle: "Le Petit Prince · 2CD访华首演纪念盘",
    meta: ["法语", "IPA", "中英对照"],
  },
{
    id: "starmania",
    language: "fr",
    cardClass: "starmania",
    href: "starmania/index.html",
    title: "星幻",
    image: "starmania/assets/show-logo.png",
    originalTitle: "Starmania",
    meta: ["法语", "IPA", "中英对照"],
  },
{
    id: "les-souliers-rouges",
    language: "fr",
    cardClass: "souliers",
    href: "les-souliers-rouges/index.html",
    title: "红舞鞋",
    image: "les-souliers-rouges/assets/show-logo.png",
    originalTitle: "Les Souliers Rouges",
    meta: ["法语", "IPA", "中英对照"],
  },
{
    id: "la-legende-du-roi-arthur",
    language: "fr",
    cardClass: "arthur",
    href: "la-legende-du-roi-arthur/index.html",
    title: "亚瑟王传奇",
    image: "la-legende-du-roi-arthur/assets/show-logo.png",
    originalTitle: "La Légende du Roi Arthur",
    meta: ["法语", "IPA", "中英对照"],
  },
{
    id: "notre-dame-de-paris",
    language: "fr",
    cardClass: "ndp",
    href: "notre-dame-de-paris/index.html",
    title: "巴黎圣母院",
    image: "notre-dame-de-paris/assets/show-logo.png",
    coverLines: ["巴黎", "圣母院"],
    originalTitle: "Notre-Dame de Paris",
    meta: ["法语", "IPA", "中英对照"],
  },
{
    id: "mozart-opera-rock",
    deployed: true,
    language: "fr",
    cardClass: "mozart",
    href: "mozart-opera-rock/index.html",
    title: "摇滚莫扎特",
    image: "mozart-opera-rock/assets/show-logo.png",
    prefetch: ["mozart-opera-rock/songs-initial.js"],
    coverLines: ["摇滚", "莫扎特"],
    originalTitle: "Mozart, l'opéra rock",
    meta: ["法语", "IPA", "中英对照"],
  },
{
    id: "romeo-et-juliette",
    deployed: true,
    language: "fr",
    cardClass: "romeo",
    href: "romeo-et-juliette/index.html",
    title: "罗密欧与朱丽叶",
    image: "romeo-et-juliette/assets/show-logo.png",
    prefetch: ["romeo-et-juliette/songs-initial.js"],
    coverLines: ["罗密欧", "与朱丽叶"],
    originalTitle: "Roméo et Juliette",
    meta: ["法语", "IPA", "中英对照"],
  },
{
    id: "le-roi-soleil",
    language: "fr",
    cardClass: "soleil",
    href: "le-roi-soleil/index.html",
    title: "太阳王",
    image: "le-roi-soleil/assets/show-logo.png",
    coverLines: ["太阳王"],
    originalTitle: "Le Roi Soleil",
    meta: ["法语", "IPA", "中英对照"],
  },
{
    id: "1789-les-amants-de-la-bastille",
    language: "fr",
    cardClass: "bastille",
    href: "1789-les-amants-de-la-bastille/index.html",
    title: "1789：巴士底狱的恋人",
    image: "1789-les-amants-de-la-bastille/assets/show-logo.png",
    coverLines: ["1789"],
    originalTitle: "Les Amants de la Bastille",
    meta: ["法语", "IPA", "中英对照"],
  },
{
    id: "don-juan",
    language: "fr",
    cardClass: "donjuan",
    href: "don-juan/index.html",
    title: "唐璜",
    image: "don-juan/assets/show-logo.png",
    coverLines: ["唐璜"],
    originalTitle: "Don Juan",
    meta: ["法语", "IPA", "中英对照"],
  },
{
    id: "moliere-le-spectacle-musical",
    deployed: true,
    language: "fr",
    cardClass: "moliere",
    href: "moliere-le-spectacle-musical/index.html",
    title: "莫里哀",
    image: "moliere-le-spectacle-musical/assets/show-logo.png",
    prefetch: ["moliere-le-spectacle-musical/songs-initial.js"],
    coverLines: ["莫里哀"],
    originalTitle: "Molière",
    meta: ["法语", "IPA", "中英对照"],
  },
{
    id: "cyrano-de-bergerac",
    language: "fr",
    cardClass: "cyrano",
    href: "cyrano-de-bergerac/index.html",
    title: "大鼻子情圣",
    image: "cyrano-de-bergerac/assets/show-logo.png",
    coverLines: ["大鼻子", "情圣"],
    originalTitle: "Cyrano de Bergerac",
    meta: ["法语", "IPA", "中英对照"],
  },
{
    id: "les-miserables-1980",
    language: "fr",
    cardClass: "lesmis-1980",
    href: "les-miserables-1980/index.html",
    title: "悲惨世界（1980法语原创概念专辑）",
    image: "les-miserables-1980/assets/show-logo.jpg",
    coverLines: ["悲惨世界", "1980 法语原创"],
    originalTitle: "Les Misérables",
    meta: ["法语", "IPA", "中英对照"],
  },
{
    id: "les-miserables-cityprod-2017",
    language: "fr",
    cardClass: "lesmis-cityprod",
    href: "les-miserables-cityprod-2017/index.html",
    title: "悲惨世界（2017 Cityprod法语版）",
    image: "les-miserables-cityprod-2017/assets/show-logo.jpg",
    coverLines: ["悲惨世界", "2017 Cityprod"],
    originalTitle: "Les Misérables en Concert",
    meta: ["法语", "IPA", "中英对照"],
  },
];

if (typeof window !== "undefined") {
  window.libraryLanguages = libraryLanguages;
  window.libraryShows = libraryShows;
}

if (typeof module !== "undefined") {
  module.exports = { libraryLanguages, libraryShows };
}
